package com.example.dndgenerator

import android.os.Parcelable
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize

data class FemaleName(
    var femaleName : String
) {
    companion object {
        val FEMALE_NAMES = listOf(
            "Adelphia",
            "Adora",
            "Adrastea",
            "Aenea",
            "Aldea",
            "Alethea",
            "Alia",
            "Alondra",
            "Aveline",
            "Alura",
            "Amadea",
            "Amarantha",
            "Amarys",
             "Andromeda",
            "Anthea",
            "Arabella",
            "Araluen",
            "Araminta",
            "Aristeia",
            "Arleth",
            "Artemis",
            "Andraste",
            "Astoria",
            "Azura",
            "Aedra",
            "Aetheria",
            "Alita",
            "Amarantia",
            "Belladonna",
            "Bethany" ,
            "Benecia",
            "Calanthe",
            "Cassandra",
            "Callidora",
            "Callista",
            "Calpernia",
            "Celestia",
            "Calindra",
            "Cyrilla",
            "Daeris",
            "Daphne",
            "Delphine",
            "Delyth",
            "Dorothea",
            "Elora",
            "Elowen",
            "Elizabeth",
            "Elysia",
            "Evangeline",
            "Evelyn",
            "Fauna",
            "Ferelith",
            "Flemeth",
            "Flora",
            "Faraday",
            "Galathea",
            "Halana",
            "Idalia",
            "Illyria",
            "Iris",
            "Izara",
            "Juno",
            "Josephine",
            "Laelia",
            "Leta",
            "Luna",
            "Lyra",
            "Leliana",
            "Lyris",
            "Meliora",
            "Merlyn",
            "Merril",
            "Morrigan",
            "Mirabella",
            "Nerys",
            "Nydia",
            "Nyx",
            "Octavia",
            "Odessa",
            "Panthea",
            "Rosella",
            "Rowan",
            "Rowena",
            "Sera",
            "Solenne",
            "Sylvia",
            "Sorine",
            "Sigrun",
            "Thea",
            "Theodora",
            "Talura",
            "Tallis",
            "Verena",
            "Vivienne",
            "Vesper",
            "Velanna",
            "Valkyria",
            "Wynne",
            "Xaviera",
            "Yreth",
            "Zephyrah",
            "Zorina"
        )
    }
}
